predictor:
  # Maximum depth for the predictor
  # (for the shortest/deviation predictor
  # it indicates the maximum number of deviations)
  max_depth: 4

# Replay buffer config
replay_buffer:
  # Maximum buffer dimension
  size: 100000
  # Batch size
  batch_size: 512
  # Buffer size
  buffer_size: 5000
  # Try to learn after this many steps
  checkpoint: 4
  # Replay buffer to restore
  load: ""
  # Save replay buffer at each checkpoint
  save: False
  # priority or random
  priority: True

dddqn:
  # Discount rate
  gamma: 0.98
  # Exploration rate
  epsilon_start: 1.0
  # Minimal exploration rate (epsilon-greedy)
  epsilon_end: 0.1
  # Decay rate for epsilon
  epsilon_decay: 0.995
  t_step: 0
  # number of steps before learning
  update_rate: 4
  # Number of steps before updating the target network
  update_network_rate: 100
  # update target network
  tau: 0.001

a2c:
  gamma: 0.99
  # actor learning rate
  alpha: 0.01
  # critic learning rate
  beta: 0.01
  t_step: 0
  update_rate: 4



training:
  active: True
  # Checkpoint interval (how often to evaluate and save the model)
  checkpoints: 500
  # Number of episodes to run
  episodes: 1500
  # Path to the model file to load
  model: ""
  # Log path
  tensorboard_path: ""
  # Console logs
  print_stats: True
  policy: "dddqn"

evaluating:
  active: False
  # Number of episodes to run
  episodes: 20
  # Path to the model file to load
  model: ""

logging:
  wandb_project: "flatland"
  wandb_entity: "llg"
  wandb_tag: "dag"